### ISSUE TITLE
Dependency on jar files for testing purposes

### ISSUE THREAD

**Issue by zonca** [det-lab/kaitai_struct_awkward_runtime#20]
@ManasviGoyal @jpivarski

I see that for testing you needed to include some `jar` files in the repository

```
$ ls lib/
com.github.scopt.scopt_2.12-3.6.0.jar       com.lihaoyi.sourcecode_2.12-0.1.4.jar
com.lihaoyi.fastparse-utils_2.12-1.0.0.jar  org.scala-lang.scala-library-2.12.12.jar
com.lihaoyi.fastparse_2.12-1.0.0.jar        org.yaml.snakeyaml-1.28.jar
```

is there a way to define those packages as requirements in the `sbt` build script of the compiler?

**Comment by ManasviGoyal** [comment]
> @ManasviGoyal @jpivarski
> 
> I see that for testing you needed to include some `jar` files in the repository
> 
> ```
> $ ls lib/
> com.github.scopt.scopt_2.12-3.6.0.jar       com.lihaoyi.sourcecode_2.12-0.1.4.jar
> com.lihaoyi.fastparse-utils_2.12-1.0.0.jar  org.scala-lang.scala-library-2.12.12.jar
> com.lihaoyi.fastparse_2.12-1.0.0.jar        org.yaml.snakeyaml-1.28.jar
> ```
> 
> is there a way to define those packages as requirements in the `sbt` build script of the compiler?

These file are generated automatically after `sbt-package` command. The user will get them along with the `kaitai-struct-compiler` tool.  I have added them in the repository just to get around issue #15.

**Comment by zonca** [comment]
I do not see them after running `sbt package`:

```
$ find . -name "*.jar"
./jvm/target/scala-2.12/kaitai-struct-compiler_2.12-0.11-SNAPSHOT.jar
./target/scala-2.12/root_2.12-0.1.0-SNAPSHOT.jar
./js/target/scala-2.12/kaitai-struct-compiler-js_sjs0.6_2.12-0.11-SNAPSHOT.jar
```

**Comment by ManasviGoyal** [comment]
> I do not see them after running `sbt package`:
> 
> ```
> $ find . -name "*.jar"
> ./jvm/target/scala-2.12/kaitai-struct-compiler_2.12-0.11-SNAPSHOT.jar
> ./target/scala-2.12/root_2.12-0.1.0-SNAPSHOT.jar
> ./js/target/scala-2.12/kaitai-struct-compiler-js_sjs0.6_2.12-0.11-SNAPSHOT.jar
> ```

It should be in a separate directory depending on your system. For me they are in `wsl.localhost\Ubuntu\usr\share\kaitai-struct-compiler\lib` 

Also, they are already added as dependecies in the `build.sbt` of `kaitai_struct_compiler`
```
libraryDependencies ++= Seq(
      "com.github.scopt" %%% "scopt" % "3.6.0",
      "com.lihaoyi" %%% "fastparse" % "1.0.0",
      "org.yaml" % "snakeyaml" % "1.28"
    )
```

**Comment by zonca** [comment]
ok, thanks,
I found them in:

    /usr/share/kaitai-struct-compiler/lib/

now, how do we tell java to automatically pick them up from there in a way that works on multiple systems?

**Comment by zonca** [comment]
I think this is fine for now,
this is just for testing with a local development version of `kaitai-struct-compiler`.
