### ISSUE TITLE
test: add more tests

### ISSUE THREAD

**Issue by ManasviGoyal** [det-lab/kaitai_struct_awkward_runtime#21]
I think it would to good to have more tests that the user can run with:
```
python -m pytest tests
```
The tests can be added for the following ksy files:
- [x] `fake.ksy`
- [x] `index_option.ksy`
- [x] `hello_world.ksy` (need to create raw data for this)
- [x] `numpy.ksy`
- [x] `pixie4e.ksy`
- [x] `records.ksy`
- [x] `scdms_v8.ksy`
- [x] `scdms.ksy` (scdms_v_two_trigger.bin can be renamed to scdms.bin and scdms_v_two_trigger.ksy can be removed)

**Comment by ManasviGoyal** [comment]
@zonca Please add these too. Thanks.

**Comment by zonca** [comment]
implementing in #24 and #25

**Comment by zonca** [comment]
implemented in #25
