### ISSUE TITLE
feat: add `awkward-kaitai` module on PyPI

### ISSUE THREAD

**Issue by ManasviGoyal** [det-lab/kaitai_struct_awkward_runtime#28]

**Comment by zonca** [comment]
try uploading the Python `awkward-kaitai` package to `PyPI` https://github.com/ManasviGoyal/kaitai_struct_awkward_runtime/tree/main/src/awkward_kaitai

**Comment by zonca** [comment]
I just did a test upload to PyPI just to check that the packaging was working correctly:
https://pypi.org/project/awkward-kaitai/

haven't tested the package yet

@ManasviGoyal @pibion @jpivarski can you send me your PyPI usernames so I can add you as maintainers of the package?

**Comment by ManasviGoyal** [comment]
It's `ManasviGoyal`.

**Comment by jpivarski** [comment]
It's `pivarski`.

**Comment by pibion** [comment]
Mine is `pibion`

**Comment by ManasviGoyal** [comment]
@zonca Please make a release for the updated awkward version and we can close this issue.

**Comment by zonca** [comment]
ok,
I released 0.1.0 both on Github and PyPI
https://pypi.org/project/awkward-kaitai/0.1.0/

I also installed it on a clean virtualenv and made sure all tests pass.
