### ISSUE TITLE
feat: use `StringBuilder` for `StrType`

### ISSUE THREAD

**Issue by ManasviGoyal** [det-lab/kaitai_struct_awkward_runtime#29]
@zonca Since `StringBuilder` is now merged in Awkward, we can use it instead of `ListOffsetBuilder<int64_t, NumpyBuilder<uint8_t>>`

**Comment by zonca** [comment]
thanks,
I am looking at the tests here:
https://github.com/scikit-hep/awkward/blob/main/header-only/tests/test_1494-layout-builder.cpp#L1865-L1889
what is the meaning of the `int64_t` type?

**Comment by ManasviGoyal** [comment]
> thanks, I am looking at the tests here: https://github.com/scikit-hep/awkward/blob/main/header-only/tests/test_1494-layout-builder.cpp#L1865-L1889 what is the meaning of the `int64_t` type?

It is the type of `offset` that we use in `ListOffsetBuilder`

**Comment by zonca** [comment]
implemented in #32
