### ISSUE TITLE
Create documentation on readthedocs

### ISSUE THREAD

**Issue by zonca** [det-lab/kaitai_struct_awkward_runtime#40]
Current documentation is on the README.md of the repository.

It would be good to setup `readthedocs` with Sphinx (like https://awkward-array.org/doc/main/getting-started/index.html) or mkdocs or similar.

We can start from README.md as "Install" and "Getting started", then details on the examples we have in https://github.com/ManasviGoyal/kaitai_struct_awkward_runtime/tree/main/example_data.

@pibion's student can provide feedback on the docs.

Let's postpone this until we have moved the 2 repositories under an organization.

**Comment by zonca** [comment]
@pibion I need admin permissions on this repository to set readthedocs up, can you please grant me those permissions?
the easiest is probably to just give admin permission to the group:

https://github.com/orgs/det-lab/teams/maintainers/repositories

**Comment by zonca** [comment]
@pibion ok, I have written docs, please check them out and provide feedback:

https://det-lab.github.io/kaitai_struct_awkward_runtime/

You can edit the pages directly using the edit button on top right of each page.

I have tested and written down 2 installation procedures, 1 for end-users using a precompiled jar attached to a release (https://github.com/det-lab/kaitai_struct_awkward_runtime/releases/tag/0.2.0) and 1 for developers compiling everything.
It would be useful to have students test them both and report errors.

Possibly @ManasviGoyal or @jpivarski want to provide feedback as well.

**Comment by ManasviGoyal** [comment]
@zonca the documentation looks good! The setup only supports Linux OS for now, right? I remember there were some issues with Windows.

**Comment by zonca** [comment]
@ManasviGoyal actually it also works on Windows under WSL, both the "user" and the "developer" installs, I updated the docs to reflect that.

**Comment by ManasviGoyal** [comment]
> @ManasviGoyal actually it also works on Windows under WSL, both the "user" and the "developer" installs, I updated the docs to reflect that.

Great! Yes, it would be good to have that in the docs. Thanks.

**Comment by zonca** [comment]
Screenshots of Awkward Kaitai running on Windows on Jetstream:

![Screenshot 2024-12-04 10 47 28](https://github.com/user-attachments/assets/80e2c33f-bb1b-475d-bb2c-4e02301e5edc)
![Screenshot 2024-12-04 14 24 14](https://github.com/user-attachments/assets/6e28fa5f-e4fb-4ab9-b051-7d9b892661f7)

Also wrote a tutorial on how to enable WSL on a Windows VM https://www.zonca.dev/posts/2024-12-04-jetstream-windows

**Comment by zonca** [comment]
I have also executed the "end user" install on Google Colab, and it works great for people want to take a look at the project without installing anything on their system.

see the "Open in Colab" button at https://det-lab.github.io/kaitai_struct_awkward_runtime/

Also, now the "end user" installation instruction page on the docs is a notebook, which is nice for testing it quickly.

I'll consider this completed, please open another issue for feedback.
