### ISSUE TITLE
Maintainers team in `det-lab`

### ISSUE THREAD

**Issue by zonca** [det-lab/kaitai_struct_awkward_runtime#41]
@pibion repositories are now under `det-lab`,
it would be useful to create a Team of Awkward-kaitai maintainers with `Maintain` permission on those 2 repositories and add me, @jpivarski and @ManasviGoyal to it.

**Comment by pibion** [comment]
@zonca I think I've got this set up now!

**Comment by zonca** [comment]
@pibion group is there, next you need to add the 2 repositories under the group

**Comment by zonca** [comment]
@pibion you need to go here: https://github.com/orgs/det-lab/teams/maintainers/repositories
and add the 2 repositories to the group.

**Comment by pibion** [comment]
@zonca thank you!  I think I've added the repositories.

**Comment by zonca** [comment]
ok, finally from https://github.com/orgs/det-lab/teams/maintainers/repositories you should be able to give "Maintain" permissions on those repos.
